name: 'Hola mundo'
description: 'Saludar a alguien y guardar la fecha'
inputs:
  who-to-greet:
    description: 'A quien saludar'
    required: true
    default: 'Mundo'
outputs:
  time:
    description: 'Fecha en que nos conocimos'
runs:
  using: 'docker'
  image: docker://alejandrofca/hello-world-docker-action
  args:
  - ${{ inputs.who-to-greet }}